// Configuration Constants for ZPL Template Creator

/**
 * History Settings
 */
export const HISTORY_LIMIT = 100;

/** Power-up height for the modal ^BY barcode defaults. */
export const BY_DEFAULT_HEIGHT = 10;

/**
 * Resident ZPL font IDs offered by the editor. Manual custom-font creation does
 * not reuse them, though an imported ^CW mapping can override one on the printer.
 */
export const BUILTIN_FONTS = ['0', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'P', 'Q', 'R', 'S', 'T', 'U', 'V'];

/**
 * The font a label uses when nothing says otherwise — matches a printer's power-up
 * ^CF (font A, height 9, width 5). DEFAULT_FONT_HEIGHT is
 * magnification 2 of font A's 9-dot cell, so a new label's text stays readable while
 * still sitting on the font's allowed grid.
 */
export const DEFAULT_FONT_ID = 'A';
export const DEFAULT_FONT_HEIGHT = 18;

/**
 * Sentinel character used to render Code 93's start/stop guard in the HRI line.
 * Labelary/Zebra draw an empty box at each end of the readable text (□CODE93□);
 * a private-use codepoint maps to the `box` charRule on font A so the renderer
 * draws that box. It never appears in real ZPL data.
 */
export const CODE93_GUARD_CHAR = '\uE000';

/**
 * Sentinel characters used to render Code 11's start/stop guards in the HRI line.
 * Labelary/Zebra draw a small hollow triangle at each end of the readable text
 * (\u25B312345611\u25B3) \u2014 the stop triangle is larger than the start one (0.75 vs 0.5 of
 * the cap height). Each private-use codepoint maps to a `triangle` charRule on font A
 * and never appears in real ZPL data.
 */
export const CODE11_GUARD_START_CHAR = '\uE001';
export const CODE11_GUARD_STOP_CHAR = '\uE002';

/**
 * Zebra renders Font 0 and the resident fonts P–V in CG Triumvirate Bold
 * Condensed. This is the browser stack that stands in for it, shared by all
 * eight so a label reads the same whichever of them a field names.
 */
const CG_TRIUMVIRATE_FAMILY = '"Roboto Condensed", "Arial Narrow", "Helvetica Condensed", Arial, sans-serif';

/**
 * Cap-ink height of that substitute face, as a fraction of the em (Roboto
 * Condensed Bold: 1472/2048). Fonts P–V convert between the printer's
 * dot-valued cap height and a canvas font size through it.
 */
const CG_TRIUMVIRATE_CAP_RATIO = 0.71875;

/**
 * Per-character render rules: replace specific glyphs with drawn shapes and/or
 * control their advance width. Keyed by character; each rule's `type` selects a
 * handler in fontMetrics.js (CHAR_RULE_HANDLERS). All ratios are fractions of
 * fontSize. Add a character by adding an entry here; add a behaviour by adding a
 * handler. The '-' rule draws a calibrated bar because the system font's hyphen
 * is too narrow/short vs Zebra's CG Triumvirate Bold Condensed dash.
 */
const CG_TRIUMVIRATE_CHAR_RULES = {
  // Real glyph. advanceRatio = cell pitch (match Zebra's digit spacing);
  // widthRatio < 1 condenses the glyph itself. Centered in the cell.
  '-': { type: 'glyph', advanceRatio: 0.903, widthRatio: 2.42, yRatio: 0.03, xRatio: 0 },
  '_': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1.3, heightRatio: 0.5, yRatio: 0.57, xRatio: 0.09 },
  '0': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '1': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '2': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '3': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '4': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '5': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '6': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '7': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '8': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '9': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.92 },
  '@': { type: 'glyph', advanceRatio: 0.90, widthRatio: 1 },
  '*': { type: 'glyph', advanceRatio: 0.48, widthRatio: 0.65, heightRatio: 0.65, xRatio: -0.009, yRatio: 0.012  },
  '$': { type: 'glyph', advanceRatio: 0.48, widthRatio: 1.1 },
  '#': { type: 'glyph', advanceRatio: 0.48, widthRatio: 1.1 },
  '!': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '(': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  ')': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '&': { type: 'glyph', advanceRatio: 0.61, widthRatio: 1.1 },
  '%': { type: 'glyph', advanceRatio: 0.903, widthRatio: 1.55 },
  '.': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  ',': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '/': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '+': { type: 'glyph', advanceRatio: 0.905, widthRatio: 1.45 },
  '=': { type: 'glyph', advanceRatio: 0.905, widthRatio: 1.53, heightRatio: 0.96, xRatio: -0.006, yRatio: 0.04 },
  '`': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '<': { type: 'glyph', advanceRatio: 1, widthRatio: 1.6 },
  '>': { type: 'glyph', advanceRatio: 1, widthRatio: 1.6 },
  '?': { type: 'glyph', advanceRatio: 0.441, widthRatio: 1 },
  ';': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  ':': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '"': { type: 'glyph', advanceRatio: 0.481, widthRatio: 1 },
  '\'': { type: 'glyph', advanceRatio: 0.296, widthRatio: 1 },
  '[': { type: 'glyph', advanceRatio: 0.295, widthRatio: 0.96, heightRatio: 0.887, xRatio: -0.024, yRatio: 0.111 },
  ']': { type: 'glyph', advanceRatio: 0.295, widthRatio: 0.96, heightRatio: 0.887, xRatio: 0.116, yRatio: 0.111 },
  'A': { type: 'glyph', advanceRatio: 0.555, widthRatio: 0.92 },
  'B': { type: 'glyph', advanceRatio: 0.555, widthRatio: 0.92 },
  'C': { type: 'glyph', advanceRatio: 0.535, widthRatio: 0.90 },
  'D': { type: 'glyph', advanceRatio: 0.59, widthRatio: 1 },
  'E': { type: 'glyph', advanceRatio: 0.5, widthRatio: 1 },
  'e': { type: 'glyph', advanceRatio: 0.48, widthRatio: 1, heightRatio: 1.01  },
  'F': { type: 'glyph', advanceRatio: 0.5, widthRatio: 1 },
  'I': { type: 'glyph', advanceRatio: 0.2763, widthRatio: 1 },
  'J': { type: 'glyph', advanceRatio: 0.445, widthRatio: 0.90 },
  'Q': { type: 'glyph', advanceRatio: 0.57, widthRatio: 1 },
  'W': { type: 'glyph', advanceRatio: 0.812, widthRatio: 1.1 },
  'R': { type: 'glyph', advanceRatio: 0.59, widthRatio: 1 },
  'T': { type: 'glyph', advanceRatio: 0.5, widthRatio: 0.90 },
  'O': { type: 'glyph', advanceRatio: 0.57, widthRatio: 1 },
  'G': { type: 'glyph', advanceRatio: 0.59, widthRatio: 1 },
  'H': { type: 'glyph', advanceRatio: 0.6101, widthRatio: 1 },
  'L': { type: 'glyph', advanceRatio: 0.481, widthRatio: 1 },
  'M': { type: 'glyph', advanceRatio: 0.755, widthRatio: 1 },
  'N': { type: 'glyph', advanceRatio: 0.6083, widthRatio: 0.99 },
  'S': { type: 'glyph', advanceRatio: 0.535, widthRatio: 1 },
  'X': { type: 'glyph', advanceRatio: 0.555, widthRatio: 1 },
  'Y': { type: 'glyph', advanceRatio: 0.555, widthRatio: 1 },
  'U': { type: 'glyph', advanceRatio: 0.609, widthRatio: 1 },
  'P': { type: 'glyph', advanceRatio: 0.555, widthRatio: 1 },
  'V': { type: 'glyph', advanceRatio: 0.535, widthRatio: 0.90 },
  'Z': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1 },
  'a': { type: 'glyph', advanceRatio: 0.461, widthRatio: 1, heightRatio: 1.01 },
  's': { type: 'glyph', advanceRatio: 0.424, widthRatio: 1 },
  'd': { type: 'glyph', advanceRatio: 0.497, widthRatio: 1, heightRatio: 1.01 },
  'f': { type: 'glyph', advanceRatio: 0.275, widthRatio: 1 },
  'g': { type: 'glyph', advanceRatio: 0.497, widthRatio: 1 },
  'h': { type: 'glyph', advanceRatio: 0.497, widthRatio: 1 },
  'H': { type: 'glyph', advanceRatio: 0.608, widthRatio: 0.946, heightRatio: 1.01, yRatio: 0.00, xRatio: 0.005 },
  'j': { type: 'glyph', advanceRatio: 0.259, widthRatio: 1 },
  'k': { type: 'glyph', advanceRatio: 0.443, widthRatio: 0.945, yRatio: 0.01, xRatio: 0.01},
  'l': { type: 'glyph', advanceRatio: 0.2585, widthRatio: 1, heightRatio: 0.96, yRatio: 0.04 },
  'w': { type: 'glyph', advanceRatio: 0.664, widthRatio: 1.1, heightRatio: 1.01},
  'r': { type: 'glyph', advanceRatio: 0.332, widthRatio: 1, heightRatio: 1.01, xRatio: 0.01 },
  't': { type: 'glyph', advanceRatio: 0.276, widthRatio: 0.90 },
  'u': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1, heightRatio: 1.01 },
  'i': { type: 'glyph', advanceRatio: 0.258, widthRatio: 1 },
  'o': { type: 'glyph', advanceRatio: 0.48, widthRatio: 1 },
  'p': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1 },
  'z': { type: 'glyph', advanceRatio: 0.387, widthRatio: 1, xRatio: 0.008 },
  'x': { type: 'glyph', advanceRatio: 0.442, widthRatio: 1 },
  'c': { type: 'glyph', advanceRatio: 0.442, widthRatio: 0.92, heightRatio: 1.01 },
  'v': { type: 'glyph', advanceRatio: 0.4425, widthRatio: 1, heightRatio: 1.01 },
  'b': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1, yRatio: 0.01 },
  'n': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1 },
  'm': { type: 'glyph', advanceRatio: 0.754, widthRatio: 1 },
  'y': { type: 'glyph', advanceRatio: 0.444, widthRatio: 1, xRatio: 0.016 },
  ' ': { type: 'glyph', advanceRatio: 0.295, widthRatio: 1 },
  '~': { type: 'glyph', advanceRatio: 1, widthRatio: 1.7 },
  '^': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1.3 },
  '{': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1.2, yRatio: 0.064, xRatio: -0.022 },
  '}': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1.2, yRatio: 0.064, xRatio: 0.018 },
  '|': { type: 'glyph', advanceRatio: 0.498, widthRatio: 1 },
};

/**
 * ZPL font mapping.
 */
export const ZPL_FONTS = {
  '0': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    yOffset: 0.01,
    baseHeight: 18,
    baseWidth: 10,
    lineHeightRatio: 1.0,
    textBlockLineHeightRatio: 1.25,
    aspectRatio: 0.9,  // Condensed - matches CG Triumvirate Bold Condensed
    // Vertical-only stretch of the drawn glyphs, as a multiple of the ^A height.
    // The substitute browser font's caps sit slightly short of Zebra's CG
    // Triumvirate Bold Condensed, so the glyphs are drawn at heightScale × the
    // em and the render frame is squeezed back by 1/heightScale — advances,
    // charRules and the ZPL height itself are unchanged, only the ink is taller.
    heightScale: 1.04,
    minHeight: 10,  // Smallest explicit height/width (dots) accepted on ZPL import;
    minWidth: 10,   // smaller positive values are clamped up. 0 stays inherit/proportional.
    wordSpacing: 0.065,  // Extra space-glyph advance as fraction of fontSize (the system font's space is narrower than Zebra's Font 0)
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
  },
  'A': {
    family: '"Bitstream Vera Sans Mono", "Lucida Console", "Courier New", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.05,
    yOffset: 0,
    capRatio: 0.73438,
    advanceRatio: 0.60205,
    lineHeightRatio: 1.286,
    textBlockLineHeightRatio: 1,
    bitmap: { magStep: 9, magWidthStep: 5, capStep: 7, advStep: 6, maxMag: 10 },
    // Code 93's start/stop guard: an empty box at each end of the HRI, sized to the
    // cap height (capRatio) and sitting on the baseline, matching Labelary/Zebra.
    charRules: {
      [CODE93_GUARD_CHAR]: { type: 'box', widthRatio: 0.37, heightRatio: 0.63, yRatio: -0.58, lineRatio: 0.06, padRatio: 0.10 },
      // Code 11's start/stop guards: small hollow up-pointing triangles, both centered
      // at the same height (yRatio) so the larger stop triangle stays aligned with the
      // start one. Sizes follow Labelary: start ≈ 0.5·cap tall, stop ≈ 0.75·cap.
      [CODE11_GUARD_START_CHAR]: { type: 'triangle', widthRatio: 0.35, heightRatio: 0.37, yRatio: -0.26, xRatio: 0.025, lineRatio: 0.05, padRatio: 0.11 },
      [CODE11_GUARD_STOP_CHAR]: { type: 'triangle', widthRatio: 0.58, heightRatio: 0.58, yRatio: -0.26, xRatio: -0.025, lineRatio: 0.05, padRatio: 0.11 },
      '_': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1, heightRatio: 2.1, yRatio: -0.459, xRatio: 0.04 },
      '-': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1.95, yRatio: -0.1, xRatio: -0.01 },
      '@': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.88, heightRatio: 0.85, xRatio: -0.014, yRatio: -0.129 },
      '=': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.98, heightRatio: 1.13, xRatio: -0.016, yRatio: -0.002 },
      '<': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.766, heightRatio: 1.46, xRatio: -0.072, yRatio: 0.108 },
      '>': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.766, heightRatio: 1.46, xRatio: 0.026, yRatio: 0.108 },
      ',': { type: 'glyph', xRatio: -0.04 },
      'B': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.95, xRatio: -0.034 },
      'C': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.013 },
      'D': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.018 },
      'E': { type: 'glyph', xRatio: -0.04 },
      'F': { type: 'glyph', xRatio: -0.04 },
      'G': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.006 },
      'H': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.019 },
      'I': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.018 },
      'J': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: 0.021 },
      'K': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.042 },
      'L': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.039 },
      'M': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.016 },
      'N': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.017 },
      'O': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.014 },
      'P': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.045 },
      'Q': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.018 },
      'R': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.044 },
      'S': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.014 },
      'T': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.005 },
      'U': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.012 },
      'V': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.008 },
      'W': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.9, xRatio: 0.002 },
      'X': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.93, xRatio: 0.007 },
      'Y': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: 0.003 },
      'Z': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.98, xRatio: -0.043 },
      '^': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.014 },
      'a': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.015 },
      'b': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.033 },
      'c': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.07 },
      'd': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: 0.004 },
      'e': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.011 },
      'f': { type: 'glyph', xRatio: 0.02 },
      'g': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: 0.004 },
      'h': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.027 },
      'i': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.026, yRatio: -0.001 },
      'j': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.052 },
      'k': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.09 },
      'l': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.009 },
      'm': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.022 },
      'n': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.026 },
      'o': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.015 },
      'p': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.032 },
      'q': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.009 },
      'r': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.09 },
      's': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.016 },
      't': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: 0.044 },
      'u': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.027 },
      'v': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.02 },
      'w': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.9, xRatio: 0.003 },
      'x': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.016 },
      'y': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: 0.028 },
      'z': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.019 },
      '{': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: 0.034 },
      '}': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.067 },
      '~': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.016 },
      '$': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.031 },
      '#': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: 0.018 },
      '&': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.96, xRatio: -0.007 },
      '(': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.038 },
      ')': { type: 'glyph', advanceRatio: 0.6018, widthRatio: 0.97, xRatio: -0.005 },
      '1': { type: 'glyph', xRatio: -0.04 },
      '+': { type: 'glyph', xRatio: -0.02, yRatio: -0.14 },
      '*': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1.14, heightRatio: 1.14, xRatio: -0.016, yRatio: 0.23 },
      ':': { type: 'glyph', xRatio: -0.1 },
      ';': { type: 'glyph', xRatio: -0.14 },
      '[': { type: 'glyph', xRatio: -0.04 },
      '!': { type: 'glyph', xRatio: -0.02 },
      '`': { type: 'glyph', xRatio: 0.08 },
      '|': { type: 'glyph', xRatio: -0.02 },
      '?': { type: 'glyph', xRatio: -0.02 },
      '"': { type: 'glyph', xRatio: -0.02 },
      '\'': { type: 'glyph', xRatio: -0.06 },
      '0': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.026 },
      '1': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.045 },
      '2': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.014 },
      '3': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.014 },
      '4': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.02 },
      '5': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.014 },
      '6': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.022 },
      '7': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.014 },
      '8': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.022 },
      '9': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.96, xRatio: -0.018 },
    },
  },
  'B': {
    family: '"Bitstream Vera Sans Mono Bold", "Lucida Console", "Courier New", monospace',
    weight: 'bold',
    monospace: true,
    uppercase: true,
    xOffset: -0.07,
    yOffset: 0,
    capRatio: 0.73438,
    advanceRatio: 0.60205,
    lineHeightRatio: 1.0,
    textBlockLineHeightRatio: 0.77,
    bitmap: { magStep: 11, magWidthStep: 7, capStep: 11, advStep: 9, maxMag: 10 },
    charRules: {
      '_': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.8, yRatio: -0.25, xRatio: -0.02 },
      '-': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1.5, yRatio: -0.11, xRatio: -0.02},
      'B': { type: 'glyph', xRatio: -0.015 },
      'C': { type: 'glyph', xRatio: -0.031 },
      'D': { type: 'glyph', xRatio: -0.022 },
      'E': { type: 'glyph', xRatio: -0.036 },
      'F': { type: 'glyph', xRatio: -0.044 },
      'G': { type: 'glyph', xRatio: -0.012 },
      'H': { type: 'glyph', xRatio: -0.012 },
      'H': { type: 'glyph', xRatio: -0.02 },
      'I': { type: 'glyph', xRatio: 0.006 },
      'J': { type: 'glyph', xRatio: -0.006 },
      'K': { type: 'glyph', xRatio: -0.014 },
      'L': { type: 'glyph', xRatio: -0.066 },
      'P': { type: 'glyph', xRatio: -0.032 },
      'R': { type: 'glyph', xRatio: -0.02 },
      'S': { type: 'glyph', xRatio: -0.02 },
      'V': { type: 'glyph', xRatio: 0.012 },
      'X': { type: 'glyph', xRatio: 0.012 },
      'Z': { type: 'glyph', xRatio: -0.022 },
    }
  },
  'C': {
    family: '"Bitstream Vera Sans Mono", "Lucida Console", "Courier New", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.08,
    yOffset: 0,
    capRatio: 0.73438,
    advanceRatio: 0.60205,
    lineHeightRatio: 1.286,
    textBlockLineHeightRatio: 1,
    bitmap: { magStep: 18, magWidthStep: 10, capStep: 14, advStep: 12, maxMag: 10 },
    charRules: {
      '_': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1, yRatio: -0.25, xRatio: 0.04 },
      '-': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1.95, yRatio: -0.1, xRatio: -0.01},
      '@': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.88, heightRatio: 0.85, xRatio: -0.014, yRatio: -0.129 },
      '=': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.98, heightRatio: 1.13, xRatio: -0.016, yRatio: -0.002 },
      '<': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.766, heightRatio: 1.46, xRatio: -0.072, yRatio: 0.108 },
      '>': { type: 'glyph', advanceRatio: 0.602, widthRatio: 0.766, heightRatio: 1.46, xRatio: 0.026, yRatio: 0.108 },
      '*': { type: 'glyph', advanceRatio: 0.602, widthRatio: 1.14, heightRatio: 1.14, xRatio: -0.016, yRatio: 0.23 },
      'A': { type: 'glyph', xRatio: 0.02 },
      'B': { type: 'glyph', xRatio: -0.016 },
      'E': { type: 'glyph', xRatio: -0.008 },
      'F': { type: 'glyph', xRatio: -0.024 },
      'J': { type: 'glyph', xRatio: 0.03 },
      'K': { type: 'glyph', xRatio: -0.02 },
      'L': { type: 'glyph', xRatio: -0.032 },
      'P': { type: 'glyph', xRatio: -0.022 },
      'R': { type: 'glyph', xRatio: -0.02},
      'T': { type: 'glyph', xRatio: 0.018},
      'V': { type: 'glyph', xRatio: 0.012},
      'X': { type: 'glyph', xRatio: 0.022},
      'Y': { type: 'glyph', xRatio: 0.02},
      'Z': { type: 'glyph', xRatio: -0.024},
      'W': { type: 'glyph', xRatio: 0.017},
      'k': { type: 'glyph', xRatio: -0.04 },
      'r': { type: 'glyph', xRatio: -0.06 },
      'p': { type: 'glyph', xRatio: -0.02 },
      't': { type: 'glyph', xRatio: 0.012 },
      'w': { type: 'glyph', xRatio: 0.015 },
    }
  },
  'D': {
    family: '"Bitstream Vera Sans Mono", "Lucida Console", "Courier New", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.07,
    yOffset: 0,
    capRatio: 0.729,
    advanceRatio: 0.622,
    lineHeightRatio: 1.286,
    textBlockLineHeightRatio: 1,
    letterSpacing: 0.0197,
    bitmap: { magStep: 18, magWidthStep: 10, capStep: 14, advStep: 12, maxMag: 10 },
    charRules: {
      '#': { type: 'glyph', xRatio: 0.04 },
      '$': { type: 'glyph', xRatio: -0.016 },
      '%': { type: 'glyph', xRatio: 0.028 },
      '&': { type: 'glyph', xRatio: 0.016 },
      '\'': { type: 'glyph', xRatio: 0.002 },
      '(': { type: 'glyph', xRatio: -0.018 },
      ')': { type: 'glyph', xRatio: 0.02 },
      '*': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.97, heightRatio: 1.15, xRatio: -0.001, yRatio: 0.228 },
      '+': { type: 'glyph', heightRatio: 1.2, xRatio: 0.002, yRatio: 0.01 },
      ',': { type: 'glyph', xRatio: 0.02 },
      '/': { type: 'glyph', xRatio: 0.012 },
      '-': { type: 'glyph', advanceRatio: 0.622, widthRatio: 2, heightRatio: 1.3, xRatio: 0.015, yRatio: -0.005 },
      '1': { type: 'glyph', xRatio: -0.026 },
      '5': { type: 'glyph', xRatio: 0.006 },
      '7': { type: 'glyph', xRatio: 0.004 },
      ';': { type: 'glyph', xRatio: 0.018 },
      '<': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.82, heightRatio: 1.5, yRatio: 0.108 },
      '=': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.8,  heightRatio: 1.28, yRatio: 0.061},
      '>': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.82, heightRatio: 1.5, xRatio: -0.003, yRatio: 0.108 },
      '?': { type: 'glyph', xRatio: -0.014 },
      '@': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.92, heightRatio: 0.87, xRatio: 0.006, yRatio: -0.136 },
      'A': { type: 'glyph', xRatio: 0.024 },
      'B': { type: 'glyph', xRatio: -0.016 },
      'C': { type: 'glyph', xRatio: 0.002},
      'D': { type: 'glyph', xRatio: -0.003},
      'E': { type: 'glyph', xRatio: -0.016},
      'F': { type: 'glyph', xRatio: -0.024},
      'G': { type: 'glyph', xRatio: 0.006},
      'I': { type: 'glyph', xRatio: 0.002},
      'J': { type: 'glyph', xRatio: 0.039},
      'K': { type: 'glyph', xRatio: -0.024},
      'L': { type: 'glyph', xRatio: -0.03},
      'M': { type: 'glyph', xRatio: 0.002},
      'P': { type: 'glyph', xRatio: -0.026},
      'R': { type: 'glyph', xRatio: -0.025},
      'T': { type: 'glyph', xRatio: 0.02},
      'V': { type: 'glyph', xRatio: 0.016},
      'W': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.94, xRatio: 0.023},
      'X': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.97, xRatio: 0.024},
      'Y': { type: 'glyph', xRatio: 0.026},
      'Z': { type: 'glyph', xRatio: -0.02},
      '[': { type: 'glyph', xRatio: -0.026},
      ']': { type: 'glyph', xRatio: 0.028},
      '^': { type: 'glyph', xRatio: 0.01},
      '_': { type: 'glyph', advanceRatio: 0.622, widthRatio: 1.02, heightRatio: 1.4, xRatio: 0.048, yRatio: -0.336 },
      'a': { type: 'glyph', xRatio: 0.008},
      'b': { type: 'glyph', xRatio: -0.016},
      'c': { type: 'glyph', xRatio: -0.008},
      'd': { type: 'glyph', xRatio: 0.017},
      'f': { type: 'glyph', xRatio: -0.006},
      'g': { type: 'glyph', xRatio: 0.018},
      'h': { type: 'glyph', xRatio: -0.004},
      'i': { type: 'glyph', xRatio: -0.008},
      'j': { type: 'glyph', xRatio: 0.015},
      'k': { type: 'glyph', xRatio: -0.044},
      'l': { type: 'glyph', xRatio: 0.01},
      'p': { type: 'glyph', xRatio: -0.016},
      'q': { type: 'glyph', xRatio: 0.01},
      'r': { type: 'glyph', xRatio: -0.07},
      't': { type: 'glyph', xRatio: 0.016},
      'u': { type: 'glyph', xRatio: -0.004},
      'w': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.94, xRatio: 0.023},
      'x': { type: 'glyph', advanceRatio: 0.622, widthRatio: 0.97, xRatio: 0.007},
      'y': { type: 'glyph', xRatio: -0.008},
      
    }
  },
  'E': {
    family: '"OCRB", "Lucida Console", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.15,
    yOffset: 3,
    capRatio: 0.73438,
    advanceRatio: 0.723,
    lineHeightRatio: 1.4,
    textBlockLineHeightRatio: 1,
    // Font E's ^FO cell top sits capPad dots per magnification above its cap ink.
    // Keep this anchor metric separate from the render-only yOffset.
    bitmap: { magStep: 28, magWidthStep: 15, capStep: 20, advStep: 20, maxMag: 10, capPad: 3 },
    charRules: {
      'B': { type: 'glyph', xRatio: 0.018 },
      'C': { type: 'glyph', xRatio: 0.033 },
      'D': { type: 'glyph', xRatio: 0.022 },
      'F': { type: 'glyph', xRatio: 0.02 },
      'G': { type: 'glyph', xRatio: 0.022 },
      'I': { type: 'glyph', xRatio: 0.018 },
      'J': { type: 'glyph', xRatio: 0.013 },
      'L': { type: 'glyph', xRatio: -0.016 },
      'N': { type: 'glyph', xRatio: 0.012 },
      'O': { type: 'glyph', xRatio: 0.018 },
      'P': { type: 'glyph', xRatio: 0.02 },
      'Q': { type: 'glyph', xRatio: 0.012 },
      'R': { type: 'glyph', xRatio: 0.006 },
      'S': { type: 'glyph', xRatio: 0.032 },
      'T': { type: 'glyph', xRatio: 0.018 },
      'U': { type: 'glyph', xRatio: 0.016 },
      'V': { type: 'glyph', xRatio: -0.014 },
      'W': { type: 'glyph', xRatio: -0.015 },
      'X': { type: 'glyph', xRatio: 0.002 },
      'Z': { type: 'glyph', xRatio: 0.008 },
    }
  },
  'F': {
    family: '"Bitstream Vera Sans Mono", "Lucida Console", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.12,
    yOffset: 0,
    capRatio: 0.727,
    advanceRatio: 0.60205,
    lineHeightRatio: 1.238,
    textBlockLineHeightRatio: 0.91,
    letterSpacing: -0.0546,
    bitmap: { magStep: 26, magWidthStep: 13, capStep: 21, advStep: 17.6, maxMag: 10 },
    charRules: {
      '!': { type: 'glyph', xRatio: -0.024},
      '"': { type: 'glyph', xRatio: -0.007},
      '#': { type: 'glyph', xRatio: 0.068},
      '$': { type: 'glyph', xRatio: -0.023},
      '%': { type: 'glyph', xRatio: 0.054},
      '&': { type: 'glyph', xRatio: 0.038},
      '\'': { type: 'glyph', xRatio: -0.01},
      '(': { type: 'glyph', xRatio: -0.012},
      ')': { type: 'glyph', xRatio: -0.01},
      ')': { type: 'glyph', xRatio: -0.01},
      '*': { type: 'glyph', advanceRatio: 0.5471, widthRatio: 0.84, heightRatio: 0.84, xRatio: -0.003, yRatio: 0.071 },
      '+': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.68, heightRatio: 0.804, xRatio: 0.016, yRatio: -0.092 },
      ',': { type: 'glyph', xRatio: 0.008},
      '-': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 1.22, heightRatio: 0.86, xRatio: -0.018, yRatio: -0.075 },
      '_': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.88, heightRatio: 0.88, xRatio: 0.044, yRatio: -0.205 },
      '.': { type: 'glyph', xRatio: -0.032},
      '/': { type: 'glyph', xRatio: 0.02},
      '0': { type: 'glyph', xRatio: 0.004},
      '1': { type: 'glyph', xRatio: -0.05},
      '4': { type: 'glyph', xRatio: 0.02},
      ':': { type: 'glyph', xRatio: -0.028},
      ';': { type: 'glyph', xRatio: -0.01},
      '<': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.853, heightRatio: 1.5, xRatio: -0.002, yRatio: 0.108 },
      '=': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.6 },
      '>': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.853, heightRatio: 1.5, xRatio: -0.006, yRatio: 0.108 },
      '?': { type: 'glyph', xRatio: -0.006},
      '@': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.788, heightRatio: 0.7, xRatio: 0.004, yRatio: -0.212 },
      'A': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.875, xRatio: 0.024 },
      'B': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.986, xRatio: -0.011 },
      'C': { type: 'glyph', xRatio: 0.002 },
      'D': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.988, xRatio: 0.003 },
      'E': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.983, xRatio: -0.025 },
      'F': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.99, xRatio: -0.035 },
      'G': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.994, xRatio: 0.021 },
      'H': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.982, xRatio: 0.003 },
      'I': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.994, xRatio: -0.025 },
      'J': { type: 'glyph', xRatio: 0.032 },
      'K': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.944, xRatio: -0.008 },
      'L': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.944, xRatio: -0.034 },
      'M': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.96, xRatio: 0.018 },
      'O': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.994, xRatio: 0.012 },
      'P': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.992, xRatio: -0.024 },
      'Q': { type: 'glyph', xRatio: 0.012 },
      'R': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.93, xRatio: -0.012 },
      'S': { type: 'glyph', xRatio: 0.002 },
      'T': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.9, xRatio: 0.018 },
      'U': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.001 },
      'V': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.9, xRatio: 0.02 },
      'W': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.82, xRatio: 0.024 },
      'X': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.85, xRatio: 0.023 },
      'Y': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.88, xRatio: 0.021 },
      'Z': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.984, xRatio: -0.006 },
      '[': { type: 'glyph', xRatio: 0.012 },
      ']': { type: 'glyph', xRatio: -0.032 },
      '^': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.989, xRatio: 0.032 },
      'a': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.995, xRatio: 0.004 },
      'b': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.984, xRatio: -0.023 },
      'c': { type: 'glyph', xRatio: -0.012 },
      'd': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.998, xRatio: 0.007 },
      'e': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.994, xRatio: 0.01 },
      'f': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.994, xRatio: -0.024 },
      'g': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.988, xRatio: 0.009 },
      'h': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.984, xRatio: -0.025 },
      'i': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.985, xRatio: -0.015 },
      'j': { type: 'glyph', xRatio: 0.022 },
      'k': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.042 },
      'l': { type: 'glyph', xRatio: -0.005 },
      'm': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: 0.014 },
      'n': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.023 },
      'o': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: 0.005 },
      'p': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.021 },
      'q': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: 0.005 },
      'r': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.076 },
      's': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.99, xRatio: -0.028 },
      't': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: 0.006 },
      'u': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: -0.022 },
      'v': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.98, xRatio: 0.02 },
      'w': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.82, xRatio: 0.025 },
      'x': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.94, xRatio: 0.024 },
      'y': { type: 'glyph', advanceRatio: 0.5472, widthRatio: 0.96, xRatio: 0.014 },
      'z': { type: 'glyph', xRatio: 0.008 },
      '{': { type: 'glyph', xRatio: -0.008 },
      '}': { type: 'glyph', xRatio: -0.009 },
      '|': { type: 'glyph', xRatio: -0.022 },
      '~': { type: 'glyph', xRatio: 0.024 },
    }
  },
  'G': {
    family: '"Bitstream Vera Sans Mono", "Lucida Console", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.002,
    capRatio: 0.73438,
    advanceRatio: 0.60205,
    lineHeightRatio: 1.25,
    letterSpacing: 0.1206,
    textBlockLineHeightRatio: 0.91,
    bitmap: { magStep: 60, magWidthStep: 40, capStep: 48, advStep: 40, maxMag: 10 },
    charRules: {
      '_': { type: 'glyph', advanceRatio: 0.7224, widthRatio: 1.2, heightRatio: 1.4, xRatio: 0.076, yRatio: -0.132 },
      '-': { type: 'glyph', advanceRatio: 0.7224, widthRatio: 1.64, xRatio: 0.04, yRatio: -0.095 },
      '(': { type: 'glyph', xRatio: -0.074 },
      ')': { type: 'glyph', xRatio: 0.07 },
      ',': { type: 'glyph', xRatio: 0.016 },
      '/': { type: 'glyph', xRatio: 0.01 },
      '$': { type: 'glyph', xRatio: -0.016 },
      '&': { type: 'glyph', xRatio: -0.008 },
      '\'': { type: 'glyph', xRatio: -0.012 },
      '*': { type: 'glyph', heightRatio: 1.188, yRatio: 0.242 },
      '+': { type: 'glyph', advanceRatio: 0.7225, widthRatio: 0.75,  xRatio: -0.016, yRatio: -0.067 },
      '1': { type: 'glyph', xRatio: -0.071 },
      '<': { type: 'glyph', advanceRatio: 0.7224, widthRatio: 0.814, heightRatio: 1.532, xRatio: -0.008, yRatio: 0.113 },
      '>': { type: 'glyph', advanceRatio: 0.7224, widthRatio: 0.814, heightRatio: 1.532, xRatio: -0.012, yRatio: 0.113 },
      '=': { type: 'glyph', advanceRatio: 0.7222, widthRatio: 0.76, xRatio: -0.01, yRatio: -0.052 },
      '@': { type: 'glyph', advanceRatio: 0.7224, widthRatio: 1.055, heightRatio: 0.89, xRatio: 0.012, yRatio: -0.134 },
      ']': { type: 'glyph', xRatio: 0.032 },
      'B': { type: 'glyph', xRatio: -0.016 },
      'E': { type: 'glyph', xRatio: -0.018 },
      'F': { type: 'glyph', xRatio: -0.024 },
      'G': { type: 'glyph', xRatio: 0.006 },
      'J': { type: 'glyph', xRatio: 0.047 },
      'K': { type: 'glyph', xRatio: -0.034 },
      'L': { type: 'glyph', xRatio: -0.028 },
      'P': { type: 'glyph', xRatio: -0.026 },
      'R': { type: 'glyph', xRatio: -0.032 },
      'Z': { type: 'glyph', xRatio: -0.024, yRatio: -0.003 },
      'b': { type: 'glyph', xRatio: -0.016 },
      'd': { type: 'glyph', xRatio: 0.014 },
      'f': { type: 'glyph', xRatio: -0.062 },
      'g': { type: 'glyph', xRatio: 0.014 },
      'i': { type: 'glyph', xRatio: -0.01 },
      'j': { type: 'glyph', xRatio: 0.086 },
      'k': { type: 'glyph', xRatio: -0.052 },
      'l': { type: 'glyph', xRatio: 0.01 },
      'p': { type: 'glyph', xRatio: -0.014 },
      'q': { type: 'glyph', xRatio: 0.008 },
      'r': { type: 'glyph', xRatio: -0.068 },
      't': { type: 'glyph', xRatio: 0.016 },
    }
  },
  'H': {
    family: '"OCRA", "Lucida Console", monospace',
    weight: 'normal',
    monospace: true,
    xOffset: -0.164,
    yOffset: 0,
    filterLowercase: true,
    capRatio: 0.78125,
    advanceRatio: 0.723,
    lineHeightRatio: 1.0,
    textBlockLineHeightRatio: 0.77,
    bitmap: { magStep: 21, magWidthStep: 13, capStep: 21, advStep: 19, maxMag: 10 }
  },
  // Legacy S-300-compatible resident fonts. These are the same CG Triumvirate Bold
  // Condensed face Font 0 scales freely, fixed to one cell per font — so they render
  // through Font 0's substitute family and its per-glyph advance corrections rather
  // than a face of their own. Only the cell is theirs: height and width snap to
  // independent integer magnifications of magStep/magWidthStep, an em maps to advStep
  // dots per width magnification, and cap ink to capStep dots per height
  // magnification. Both line pitches then work out to exactly one cell per line —
  // ^FB steps a ratio of the cap ink, ^TB a ratio of the em, hence the capRatio in
  // the second. capPad is the ascender space above the cap ink, for ^FT anchoring.
  'P': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 3,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 20 / 12,
    textBlockLineHeightRatio: (20 * CG_TRIUMVIRATE_CAP_RATIO) / 12,
    bitmap: { magStep: 20, magWidthStep: 18, capStep: 12, advStep: 16.15, maxMag: 10, capPad: 3 }
  },
  'Q': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 4,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 28 / 17,
    textBlockLineHeightRatio: (28 * CG_TRIUMVIRATE_CAP_RATIO) / 17,
    bitmap: { magStep: 28, magWidthStep: 24, capStep: 17, advStep: 22.71, maxMag: 10, capPad: 4 }
  },
  'R': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 4.2,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 35 / 22.6,
    textBlockLineHeightRatio: (35 * CG_TRIUMVIRATE_CAP_RATIO) / 22.6,
    bitmap: { magStep: 35, magWidthStep: 31, capStep: 22.6, advStep: 29.34, maxMag: 10, capPad: 4 }
  },
  'S': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 5.4,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 40 / 25.5,
    textBlockLineHeightRatio: (40 * CG_TRIUMVIRATE_CAP_RATIO) / 25.5,
    bitmap: { magStep: 40, magWidthStep: 35, capStep: 25.5, advStep: 33.39, maxMag: 10, capPad: 5 }
  },
  'T': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 6.2,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 48 / 31,
    textBlockLineHeightRatio: (48 * CG_TRIUMVIRATE_CAP_RATIO) / 31,
    bitmap: { magStep: 48, magWidthStep: 42, capStep: 31, advStep: 39.49, maxMag: 10, capPad: 5 }
  },
  'U': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 7.6,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 59 / 38,
    textBlockLineHeightRatio: (59 * CG_TRIUMVIRATE_CAP_RATIO) / 38,
    bitmap: { magStep: 59, magWidthStep: 53, capStep: 38, advStep: 50.08, maxMag: 10, capPad: 6 }
  },
  'V': {
    family: CG_TRIUMVIRATE_FAMILY,
    weight: 'bold',
    monospace: false,
    wordSpacing: 0.065,
    yOffset: 10.5,
    charRules: CG_TRIUMVIRATE_CHAR_RULES,
    capRatio: CG_TRIUMVIRATE_CAP_RATIO,
    lineHeightRatio: 80 / 51.4,
    textBlockLineHeightRatio: (80 * CG_TRIUMVIRATE_CAP_RATIO) / 51.4,
    bitmap: { magStep: 80, magWidthStep: 71, capStep: 51.4, advStep: 66.65, maxMag: 10, capPad: 10 }
  },
  // Default fallback
  'default': {
    family: 'Arial, sans-serif',
    weight: 'normal',
    monospace: false,
    lineHeightRatio: 1.0,
    textBlockLineHeightRatio: 1.0,
    aspectRatio: 1.0
  }
};
